### ISSUE TITLE
Issue in super_player example, Chapter 04. Missed use::crate.

### ISSUE THREAD

**Issue by kalwalt** [PacktPublishing/Mastering-RUST-Second-Edition#8]
In the super_player example in the [main.rs](https://github.com/PacktPublishing/Mastering-RUST-Second-Edition/blob/master/Chapter04/super_player/src/main.rs) file it's needed to make this change:

```diff
mod media;
- 
+ use crate::media::Playable;
```
Otherwise you will get an error and the build process will fail. In the Book is mentioned but it is missed.

**Comment by creativcoder** [comment]
Hey @kalwalt Good find! I would love a PR for this :)

**Comment by kalwalt** [comment]
@creativcoder  will do it!

**Comment by creativcoder** [comment]
Thanks for the PR!

**Comment by kalwalt** [comment]
It's a pleasure!
